// import {NextIntlClientProvider, hasLocale} from 'next-intl';
import type { Metadata } from "next";
import { Nunito, PT_Sans } from "next/font/google";
import "./globals.css";
// import {notFound} from 'next/navigation';
// import {routing} from '@/i18n/routing';
import { ThemeProvider } from "@/components/theme-provider";
import ReduxProvider from "@/components/redux-provider";
import { PeachyProvider } from "@/context/peachy";
import { Toaster } from "@/components/ui/sonner";

const nunito = Nunito({
  variable: "--font-nunito",
  subsets: ["latin"],
});

const ptSans = PT_Sans({
  variable: "--font-pt-sans",
  subsets: ["latin"],
  weight: ["400", "700"],
});

export const metadata: Metadata = {
  title: "PEACHY GANG",
  description:
    "PEACHY is an application inspired by Mitao Cat between Peach and Goma.",
};

export default async function LocaleLayout({
  children,
}: // params
{
  children: React.ReactNode;
  // params: Promise<{locale: string}>;
}) {
  // const {locale} = await params;
  // if (!hasLocale(routing.locales, locale)) {
  //   notFound();
  // }

  return (
    <html lang="en" className="light" suppressHydrationWarning>
      <head>
        <title>PEACHY GANG</title>
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/images/favicon.ico" />
        {/*<link rel="apple-touch-icon" href="/apple-touch-icon.png" />*/}
        <meta name="theme-color" content="#000000" />
        <meta name="description" content="Generated by create next app" />
        <meta
          name="keywords"
          content="nextjs, react, typescript, tailwindcss, peachy gang"
        />
        <script
          dangerouslySetInnerHTML={{
            __html: `
        document.body.removeAttribute('cz-shortcut-listen');
      `,
          }}
        />
      </head>
      <body
        className={`${nunito.variable} ${ptSans.variable} antialiased relative`}
        cz-shortcut-listen="true"
      >
        {/*<NextIntlClientProvider>*/}
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <ReduxProvider>
            <PeachyProvider>
              <div className="texture" />
              {children}
              <Toaster position="top-right" />
            </PeachyProvider>
          </ReduxProvider>
        </ThemeProvider>
        {/*</NextIntlClientProvider>*/}
      </body>
    </html>
  );
}
